import 'package:flutter/material.dart';
import '../route_registry.dart';

/// Dynamic route resolver that resolves routes without app imports
/// Uses module exports to access widgets dynamically
class RouteResolver {
  /// Resolve a route widget from a route definition
  /// Returns a WidgetBuilder for the route
  WidgetBuilder? resolveRoute(String widgetPath) {
    try {
      // Parse widget path like "auth_module.screens.LoginScreen"
      final parsed = _parseWidgetPath(widgetPath);
      if (parsed == null) {
        return null;
      }

      // Since Dart doesn't support runtime imports, we'll use code generation
      // to create an internal route cache that maps widget paths to builders
      // For now, return null - will be resolved from cache
      return _resolveFromCache(widgetPath, parsed);
    } catch (e) {
      print('Warning: Failed to resolve route widget "$widgetPath": $e');
      return null;
    }
  }

  /// Parse widget path like "package.screens.WidgetName"
  Map<String, String>? _parseWidgetPath(String widgetPath) {
    final parts = widgetPath.split('.');
    if (parts.length < 3) {
      return null;
    }

    final packageName = parts[0];
    final namespace = parts[1]; // e.g., 'screens', 'widgets', etc.
    final className = parts[2];

    // Convert class name to file name (snake_case)
    final fileName = _toSnakeCase(className);

    return {
      'package': packageName,
      'namespace': namespace,
      'className': className,
      'fileName': fileName,
      'import': 'package:$packageName/$namespace/$fileName.dart',
    };
  }

  /// Resolve widget from internal cache
  /// The cache is generated at build time with all route mappings
  WidgetBuilder? _resolveFromCache(
    String widgetPath,
    Map<String, String> parsed,
  ) {
    // The cache will be generated by the build command
    // For now, return null - will be implemented with code generation
    return null;
  }

  /// Build all routes from RouteRegistry
  /// Returns a map of route paths to WidgetBuilders
  Map<String, WidgetBuilder> buildRoutesFromRegistry(
    RouteRegistry routeRegistry,
  ) {
    final routes = <String, WidgetBuilder>{};

    // Get all routes from registry
    final allRoutes = routeRegistry.getAllRoutes();

    for (final route in allRoutes) {
      final builder = resolveRoute(route.widget);
      if (builder != null) {
        routes[route.path] = builder;
      } else {
        print(
          'Warning: Could not resolve route widget "${route.widget}" for path "${route.path}"',
        );
      }
    }

    return routes;
  }

  /// Convert StudlyCase to snake_case
  static String _toSnakeCase(String input) {
    return input
        .replaceAllMapped(
          RegExp(r'([A-Z])'),
          (match) => '_${match.group(1)!.toLowerCase()}',
        )
        .replaceFirst(RegExp(r'^_'), '');
  }
}

